name: null

channels:
    - conda-forge
    - defaults

dependencies:
    - jupyterlab
    - python=3.13
    - numpy>2.0
    - matplotlib-base
    - matplotlib-inline
    - scikit-learn
    - scikit-image
    - pandas
